name: FlareSolverr Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Pull Docker image
      run: docker pull ghcr.io/flaresolverr/flaresolverr:v3.3.16

    - name: Run FlareSolverr
      run: docker run -d --name flaresolverr-container -p 8191:8191 ghcr.io/flaresolverr/flaresolverr:v3.3.16

    - name: Check container status
      run: docker ps

    - name: Fetch container logs
      run: docker logs flaresolverr-container

    - name: Check if container is reachable
      run: |
        curl -L -X POST 'http://localhost:8191/v1' \
        -H 'Content-Type: application/json' \
        --data-raw '{"cmd": "request.get", "url": "http://www.example.com", "maxTimeout": 60000}'

    - name: Stop FlareSolverr container
      run: docker stop flaresolverr-container
