name: FlareSolverr Workflow

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      RUST_BACKTRACE: 1
    
    steps:
    - name: Set RUST_BACKTRACE environment variable
      run: export RUST_BACKTRACE=full
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # You can specify '3.11' or any later version you prefer
        architecture: 'x64'      # Adjust as needed, e.g., 'x86', 'x64', 'arm64'

    - name: Setup requirements.txt
      run: pip install -r requirements.txt

    - name: Setup rarfile
      run: pip install rarfile
     #https://github.com/pnxenopoulos/awpy@awpy2
    - name: Setup Awpy
      run: pip install git+https://github.com/hojlund123/awpy@awpy2

    - name: Pull Docker image
      run: docker pull ghcr.io/flaresolverr/flaresolverr:v3.3.21
      #therealbix/flaresolverr
      #ghcr.io/flaresolverr/flaresolverr:v3.3.17

    - name: Run FlareSolverr
      run: docker run -d --name flaresolverr-container -p 8191:8191 ghcr.io/flaresolverr/flaresolverr:v3.3.21
      #therealbix/flaresolverr
      #ghcr.io/flaresolverr/flaresolverr:v3.3.16

    - name: Wait for FlareSolverr to start
      run: sleep 20

    - name: Run Python script
      run: python demos.py

    - name: List folders
      run: du -h

    - name: List filesized
      run: ls -l
      
    - name: Fetch container logs 2
      run: timeout 1m docker logs -f flaresolverr-container || true
      
    - name: Commit and push demo file
      run: |
        git config --local user.email "hojlund123@live.dk"
        git config --local user.name "researchersec[bot]"
        git add "lan/*"
        git add "online/*"
        git commit -m "Added demo file"
        git push

