name: FlareSolverr Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Pull Docker image
      run: docker pull ghcr.io/flaresolverr/flaresolverr:v3.3.16

    - name: Run FlareSolverr
      run: docker run -d --name flaresolverr-container -p 8191:8191 ghcr.io/flaresolverr/flaresolverr:v3.3.16

    - name: Get container IP address
      id: get_container_ip
      run: echo "::set-output name=container_ip::$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' flaresolverr-container)"

    - name: Run Python script
      run: python scraper.py ${{ steps.get_container_ip.outputs.container_ip }}

    - name: Stop FlareSolverr container
      run: docker stop flaresolverr-container
